# gRPC
grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

# Spring
spring:
  main:
    web-application-type: none
  datasource:
    driverClassName: 'org.postgresql.Driver'
    url: 'jdbc:postgresql://localhost:5432/smart-home-tech'
    username: 'user'
    password: 'password'
  jpa:
    show_sql: true
    hibernate.ddl-auto: none
    properties.hibernate:
      jdbc.time_zone: UTC
      format_sql: true
  sql.init.mode: always

# Logging
logging:
  level:
    root: INFO
    telemetry.analyzer: DEBUG

# Kafka custom properties
kafka:
  server: 'localhost:9092'
  topics:
    hubs: 'telemetry.hubs.v1'
    snapshots: 'telemetry.snapshots.v1'